## 01 - Introduction To NumPY

---
Importing NumPY

In [1]:
import numpy as np

---
### Initialization of Array in NumPY
From Python Lists

In [2]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


---
Array with Evenly Spaced Numbers

Syntax -> numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None, axis = 0)

In [3]:
arr = np.linspace(3.5, 10, 3, dtype = np.float64)
print(arr)

[ 3.5   6.75 10.  ]


---
Array with Garbage Value

In [4]:
arr = np.empty([4, 3], dtype = np.int32, order = 'f')
print(arr)

[[1918990176 1701996900 2037669920]
 [1735289198 2037150819 1735289200]
 [1635200627 1919885356 1885692974]
 [ 543190642 1702065440 1633903986]]


---
Array with Zeros

In [5]:
arr = np.zeros([2, 3], dtype = np.int32, order = 'f') # [Dimension of Array]
print(arr)

[[0 0 0]
 [0 0 0]]


---
Array with Ones

In [6]:
arr = np.ones((2, 2), dtype = np.int32, order = 'f') # [Dimension of Array]
print(arr)

[[1 1]
 [1 1]]


---
Array with All Values Equal

In [7]:
arr = np.full((2, 2), 7)
print(arr)

[[7 7]
 [7 7]]


---
Array with Range Values

In [8]:
arr = np.arange(0, 10, 2, dtype = np.int64) # (start, end, steps), end is excluded
print(arr)

[0 2 4 6 8]


---
### Indexing in NumPY

In 1D Array

In [9]:
arr = np.array([10, 20, 30, 40, 50])
              #  0,  1,  2,  3,  4
              # -5, -4, -3, -2, -1
print(arr[2])
print(arr[-1])

30
50


---
In 2D Array

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1, 0]) # [Row, Column]

4


---

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# all rows, second column
print(arr[:, 1])
# [2 5]
print(arr[:, [1]])
# [[2]
#  [5]]

# all, rows, second and third column
print(arr[:, [1, 2]])
# [[2 3]
#  [5 6]]

[2 5]
[[2]
 [5]]
[[2 3]
 [5 6]]


---
[start:stop(excluded):steps]

In [12]:
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[1:6:2])

[1 3 5]


---

In [13]:
arr = np.random.rand(4, 4, 4)
print(arr[..., 0])

[[0.51074239 0.64768674 0.14243495 0.25669324]
 [0.30954437 0.86936132 0.79026178 0.57669783]
 [0.19006706 0.01033631 0.35444351 0.78007071]
 [0.32919705 0.25411337 0.71051205 0.79168342]]


---

In [14]:
arr = np.array([1, 2, 0, 4, 5, 3])

idx = np.array([1, 3, 5])
print (arr[idx])

print (arr[(arr != 0) | (arr == 0)])

[2 4 3]
[1 2 0 4 5 3]


---

In [15]:
arr = np.array([1, 2, 3])
print(arr[:, np.newaxis])

[[1]
 [2]
 [3]]


---

In [16]:
arr = np.array([1, 2, 3, 4])
arr[1:3] = 99
print(arr)

[ 1 99 99  4]


---
### Arithmetic Operations in NumPY Arrays

In [17]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


---
### Absolute in NumPY

In [18]:
arr = np.array([-3, -1, 0, 1, 3])
res = np.absolute(arr)

print(res)

[3 1 0 1 3]


---
### Add in Numpy

In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
res = np.add(arr1, arr2)

print(res)

[5 7 9]


---
### Exponentiation in NumPY

In [20]:
arr1 = np.array([5, 72, 13, 100])
arr2 = np.array([2, 5, 10, 30])

res = np.power(arr1, arr2)
print(res)

[                 25          1934917632        137858491849
 1152921504606846976]


---
### Modulus in NumPY

In [21]:
arr1 = np.array([5, 72, 13, 100])
arr2 = np.array([2, 5, 10, 30])

res = np.mod(arr1, arr2)
print(res)

[ 1  2  3 10]


---
### Sine / Exponential / Square Root in NumPy

In [22]:
a = np.array([0, np.pi/2, np.pi])
print(np.sin(a))
print(np.exp(a))
print(np.sqrt(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          4.81047738 23.14069263]
[0.         1.25331414 1.77245385]


---
### Sorting NumPY Arrays

In [23]:
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
          ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

arr = np.array(values, dtype = dtypes)

print (np.sort(arr, order = 'name'))
print (np.sort(arr, order = ['grad_year', 'cgpa']))

[(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
[(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


---
### Type Of NumPY Arrays

In [24]:
arr = np.array([1, 2, 3])
print(type(arr))

<class 'numpy.ndarray'>


---
### Shape / Size / DataType of NumPY Arrays

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape :", arr.shape)
print("Size :", arr.size)
print("D Type :", arr.dtype)

Shape : (2, 3)
Size : 6
D Type : int64


---
### Formiter in NumPY

In [26]:
var = "RafatAlam"
arr = np.fromiter(var, dtype = 'U2')

print(arr)

['R' 'a' 'f' 'a' 't' 'A' 'l' 'a' 'm']


---
### Random In NumPY

Fills values with random values between [0, 1)

In [27]:
arr = np.random.rand(2, 3)
print(arr)

[[0.34219176 0.45606934 0.0546637 ]
 [0.95455738 0.39679941 0.88735542]]


---
Fill values with standard Normal Distribution

In [28]:
arr = np.random.randn(2, 2)
print(arr)

[[ 0.8348876   0.60801478]
 [ 1.34418053 -0.14787315]]


---
Fills values with random integers between [a, b)

In [29]:
arr = np.random.randint(1, 10, size = [2, 3])
print(arr)

[[4 1 3]
 [1 4 9]]


---
### Matrix creation in NumPY
Identity Matrix

In [30]:
arr = np.eye(3, dtype = np.int64)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


---
Diagonal Matrix

In [31]:
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


---
Zero Array

In [32]:
arr = np.zeros_like(arr) # Pass array it will take shape of that
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


---
One's Array

In [33]:
arr = np.ones_like(arr) # Pass array it will take shape of that
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


---
### Reshaping Arrays

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print(str(arr))

res = arr.reshape((2, 8))
print(res)
res = np.reshape(arr, [4, -1])
print(res)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


---
### Resizing Arrays
Permanent Array Reshaping

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize(2, 3)
print(arr)

[[1 2 3]
 [4 5 6]]


---

## 02 - Stacking and Splitting Arrays
---

Importing NumPY

In [36]:
import numpy as np

---
### Stacking 2 [1-D Arrays]

In [37]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

res = np.stack((arr1, arr2), axis = 0)
print(res)

[[1 2 3]
 [4 5 6]]


In [38]:
res = np.stack((arr1, arr2), axis = 1)
print(res)

[[1 4]
 [2 5]
 [3 6]]


In [39]:
res = np.stack((arr1, arr2), axis = -1) # -1 represents 'last dimension-wise'. Here 2 axis are possible. 0 and 1. So, -1 is same as 1.
print(res)

[[1 4]
 [2 5]
 [3 6]]


---
### Splitting Arrays in NumPY

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
res = np.array_split(arr, 3)
print(res)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [41]:
arr = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])
res = np.split(arr, 3, axis = 1)
print(res)

[array([[3],
       [8],
       [4]]), array([[2],
       [9],
       [6]]), array([[1],
       [7],
       [5]])]


---
V-Split is for axis = 0

In [42]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

res = np.vsplit(arr, 2)
print(res)
res = np.split(arr, 2, axis = 0)
print(res)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


---
H-Split is for axis = 1

In [43]:
res = np.hsplit(arr, 2)
print(res)
res = np.split(arr, 2, axis = 1)
print(res)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


---
D-Split is for axis = 2

In [44]:
arr = np.array([[[0, 1, 2, 3],
                 [4, 5, 6, 7],
                 [8, 9, 10, 11]],

                [[12, 13, 14, 15],
                 [16, 17, 18, 19],
                 [20, 21, 22, 23]]])

res = np.dsplit(arr, 2)
print(res)

[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


---

## 03 - Array Broadcasting
---
Importing NumPY

In [45]:
import numpy as np

---
Operation always happens row-wise

In [46]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

print(a + b)

[[2 4 6]
 [5 7 9]]


---


By using np.newaxis, we can add elements column-wise

In [47]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])

print(a + b[:, np.newaxis])

[[2 3 4]
 [6 7 8]]


---
### Broadcasting in Conditional Operations

In [48]:
ages = np.array([12, 24, 35, 45, 60, 72])
age_group = np.array(["Adult", "Minor"])

res = np.where(ages >= 18, age_group[0], age_group[1])
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


---
### Normalizing Data in ML
- centers data and it has zero mean.
- By dividing the standard deviation, its ensures unit variance.

In [49]:
arr = np.array([
  [100, 120, 130],
  [90, 110, 140],
  [80, 100, 120]
])

mean = arr.mean(axis = 0)
std = arr.std(axis = 0)

normalized_arr = (arr - mean) / std
print(normalized_arr)

[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


---
### Centering Data in ML

In [50]:
arr = np.array([
  [10, 20],
  [15, 25],
  [20, 30]
])

mean = arr.mean(axis = 0)
centered_arr = arr - mean
print(centered_arr)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]


---

## 04 - Aggregation / Universal Functions
---
Importing NumPY

In [51]:
import numpy as np

---
## Sum in NumPY

In [52]:
arr = [20, 2, .2, 10, 4] 

print("Sum :", np.sum(arr))
print("Data Type :", np.sum(arr).dtype)

print("Sum (int32) :", np.sum(arr, dtype = np.int32))

Sum : 36.2
Data Type : float64
Sum (int32) : 36


---

In [53]:
arr = [[14, 17, 12, 33, 44],
	     [15, 6, 27, 8, 19],
	     [23, 2, 54, 1, 4,]]

print("Sum :", np.sum(arr))
print("Data Type :", np.sum(arr).dtype)

Sum : 279
Data Type : int64


---

In [54]:
arr = [[14, 17, 12, 33, 44],
	     [15, 6, 27, 8, 19],
	     [23, 2, 54, 1, 4,]]

print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))
print(np.sum(arr, axis = 1, keepdims = True))

[52 25 93 42 67]
[120  75  84]
[[120]
 [ 75]
 [ 84]]


---
### Mean in NumPY

In [55]:
arr = [20, 2, 7, 1, 34]
print(np.mean(arr))

12.8


---

In [56]:
arr = [[14, 17, 12, 33, 44],  
       [15, 6, 27, 8, 19], 
       [23, 2, 54, 1, 4]]

print(np.mean(arr))
print(np.mean(arr, axis = 0))
print(np.mean(arr, axis = 1))

18.6
[17.33333333  8.33333333 31.         14.         22.33333333]
[24.  15.  16.8]


---
### Max / Min in NumPY

In [57]:
num1 = 11
num2 = 21

res = np.maximum(num1, num2)
print(res)
res = np.minimum(num1, num2)
print(res)

21
11


---

In [58]:
num1 = [2, 8, 125]
num2 = [3, 3, 15]

res = np.maximum(num1, num2)
print(res)
res = np.minimum(num1, num2)
print(res)

[  3   8 125]
[ 2  3 15]


---

In [59]:
num1 = [np.nan, 0, np.nan]
num2 = [np.nan, np.nan, 0]

res = np.maximum(num1, num2)
print(res)
res = np.minimum(num1, num2)
print(res)

[nan nan nan]
[nan nan nan]


---
### Trignometric Functions

In [60]:
angles = np.array([0, 30, 45, 60, 90, 180]) 

radians = np.deg2rad(angles)

# sine of angles
sine = np.sin(radians)
print(np.sin(radians))

# inverse sine of sine values
print(np.rad2deg(np.arcsin(sine)))

# hyperbolic sine of angles
sineh = np.sinh(radians)
print(np.sinh(radians))

# inverse sine hyperbolic 
print(np.sin(sineh)) 

# hypotenuse
print(np.hypot(3, 4))

[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]
[0.0000000e+00 3.0000000e+01 4.5000000e+01 6.0000000e+01 9.0000000e+01
 7.0167093e-15]
[ 0.          0.54785347  0.86867096  1.24936705  2.3012989  11.54873936]
[ 0.          0.52085606  0.76347126  0.94878485  0.74483916 -0.85086591]
5.0


---
### Statical Functions

In [61]:
arr = np.array([50.7, 52.5, 50, 58, 55.63, 73.25, 49.5, 45])

# minimum and maximum 
print(np.amin(arr), np.amax(arr))

# range of arr i.e. max - min
print(np.ptp(arr))

# percentile -> Value below which 70 % student fall
print(np.percentile(arr, 70))
 
# mean 
print(np.mean(arr))

# median 
print(np.median(arr))

# standard deviation 
print(np.std(arr))

# variance 
print(np.var(arr))

# average 
print(np.average(arr))

45.0 73.25
28.25
55.317
54.3225
51.6
8.052773978574091
64.84716875
54.3225


---
### Bit-twiddling Functions

In [62]:
even = np.array([0, 2, 4, 6, 8, 16, 32])
odd = np.array([1, 3, 5, 7, 9, 17, 33])

# bitwise_and
print(np.bitwise_and(even, odd))

# bitwise_or
print(np.bitwise_or(even, odd))

# bitwise_xor
print(np.bitwise_xor(even, odd))
 
# invert or not
print(np.invert(even))

# left_shift 
print(np.left_shift(even, 1))

# right_shift 
print(np.right_shift(even, 1))

[ 0  2  4  6  8 16 32]
[ 1  3  5  7  9 17 33]
[1 1 1 1 1 1 1]
[ -1  -3  -5  -7  -9 -17 -33]
[ 0  4  8 12 16 32 64]
[ 0  1  2  3  4  8 16]


---

## 05 - Linear Algebra with NumPY
---
Importing NumPY

In [63]:
import numpy as np

---
### Transpose of Matrix

In [64]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


---
### Matrix Multiplication / Dot Product

In [65]:
arr1 = np.array([[1, 2], [4, 5]])
arr2 = np.array([[7, 8], [9, 10]])

print(np.dot(arr1, arr2))
print(np.vdot(arr1, arr2)) # It assumes array to be flattened

vector_a = 2 + 3j
vector_b = 4 + 5j

print(np.dot(vector_a, vector_b))
print(np.vdot(vector_a, vector_b)) # It will take conjugate of complex numbers for dot product

[[25 28]
 [73 82]]
109
(-7+22j)
(23-2j)


---
### Inner Product

In [66]:
arr1 = np.array([2, 6])     # 1 x 2
arr2 = np.array([3, 10])    # 2 x 1

print(np.inner(arr1, arr2)) # 1 x 1

arr1 = np.array([[2, 3, 4], [3, 2, 9]])  # 2 x 3
arr2 = np.array([[1, 5, 0], [5, 10, 3]]) # 3 x 2

print(np.inner(arr1, arr2))              # 2 x 2

66
[[17 52]
 [13 62]]


---
### Outer Product

In [67]:
arr1 = np.array([2, 6])
arr2 = np.array([3, 10])

print(np.outer(arr1, arr2))

arr1 = np.array([[3, 6, 4], [9, 4, 6]])
arr2 = np.array([[1, 15, 7], [3, 10, 8]])

print(np.outer(arr1, arr2))

[[ 6 20]
 [18 60]]
[[  3  45  21   9  30  24]
 [  6  90  42  18  60  48]
 [  4  60  28  12  40  32]
 [  9 135  63  27  90  72]
 [  4  60  28  12  40  32]
 [  6  90  42  18  60  48]]


---
### Cross Product

In [68]:
arr1 = np.array([3, 6, 0])
arr2 = np.array([9, 10, 0])

print(np.cross(arr1, arr2))

arr1 = np.array([[2, 6, 9], [2, 7, 3]])
arr2 = np.array([[7, 5, 6], [3, 12, 3]])

print(np.cross(arr1, arr2))

[  0   0 -24]
[[ -9  51 -32]
 [-15   3   3]]


---
### Dterminant of a Matrix
Using log of determinant

In [69]:
arr = np.array([[50, 29], [30, 44]])
sign, logdet = np.linalg.slogdet(arr)
res = sign * np.exp(logdet)
print(res)

1330.0000000000002


---
Using simple Determinant (Used for small values)

In [70]:
arr = np.array([[1, 2], [3, 4]])
res = np.linalg.det(arr)
print(res)

-2.0000000000000004


---
__Using LU Decomposition :__ LU decomposition can also be used to calculate the determinant by decomposing the matrix into lower (L) and upper (U) triangular matrices. The determinant is the product of the diagonal elements of the U matrix.

In [71]:
import scipy.linalg
arr = np.array([[1, 2], [3, 4]])
P, L, U = scipy.linalg.lu(arr)
res = np.prod(np.diag(U))
print(res)

2.0


---
### Inverse of a Matrix

In [72]:
arr = np.array([[6, 1, 1],
                [4, -2, 5],
                [2, 8, 7]])
print(np.linalg.inv(arr))

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


---