In [ ]:
import numpy as np

---

## Baiscs of NumPY Arrays

---

In [ ]:
arr = np.array([1, 2, 3, 4])
print(type(arr))

---

In [ ]:
arr = np.array([[0, 4, 2],
                [3, 4, 5],
                [23, 4, 5],
                [2, 34, 5],
                [5, 6, 7]])

print(arr.shape)

---

In [ ]:
arr = np.array([[0, 4, 2]])
print(arr.dtype)

arr = np.array([0.2, 0.4, 2.4])
print(arr.dtype)

---

## Numpy Array Boardcasting

---
Modifying array on basis of conditional statements

In [ ]:
ages = np.array([12, 24, 35, 45, 60, 72])
age_group = np.array(["Adult", "Minor"])

res = np.where(ages >= 18, age_group[0], age_group[1])
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


---
Multiplying elements column-wise

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([10, 20])
res = a * b

print(res)

[[10 40]
 [30 80]]


---
We are adding numbers row-wise by using np.newasix

In [ ]:
arr1 = np.array([
  [30, 32, 34, 33, 31],  
  [25, 27, 29, 28, 26], 
  [20, 22, 24, 23, 21]  
])

arr2 = np.array([1.5, -0.5, 2.0])

res = arr1 + arr2[:, np.newaxis]
print(res)


[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]
