## 01 - Introduction To NumPY

---
Importing NumPY

In [1]:
import numpy as np

---
### Initialization of Array in NumPY
From Python Lists

In [2]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


---
Array with Evenly Spaced Numbers

Syntax -> numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None, axis = 0)

In [3]:
arr = np.linspace(3.5, 10, 3, dtype = np.float64)
print(arr)

[ 3.5   6.75 10.  ]


---
Array with Garbage Value

In [4]:
arr = np.empty([4, 3], dtype = np.int32, order = 'f')
print(arr)

[[4128860 6619251 7602273]
 [6029375 7536754 4259932]
 [3801155 7471196 7340144]
 [5570652 6684769 6357060]]


---
Array with Zeros

In [5]:
arr = np.zeros([2, 3], dtype = np.int32, order = 'f') # [Dimension of Array]
print(arr)

[[0 0 0]
 [0 0 0]]


---
Array with Ones

In [6]:
arr = np.ones((2, 2), dtype = np.int32, order = 'f') # [Dimension of Array]
print(arr)

[[1 1]
 [1 1]]


---
Array with All Values Equal

In [7]:
arr = np.full((2, 2), 7)
print(arr)

[[7 7]
 [7 7]]


---
Array with Range Values

In [8]:
arr = np.arange(0, 10, 2, dtype = np.int64) # (start, end, steps), end is excluded
print(arr)

[0 2 4 6 8]


---
### Indexing in NumPY

In 1D Array

In [9]:
arr = np.array([10, 20, 30, 40, 50])
              #  0,  1,  2,  3,  4
              # -5, -4, -3, -2, -1
print(arr[2])
print(arr[-1])

30
50


---
In 2D Array

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1, 0]) # [Row, Column]

4


---

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# all rows, second column
print(arr[:, 1])
# [2 5]
print(arr[:, [1]])
# [[2]
#  [5]]

# all, rows, second and third column
print(arr[:, [1, 2]])
# [[2 3]
#  [5 6]]

[2 5]
[[2]
 [5]]
[[2 3]
 [5 6]]


---
[start:stop(excluded):steps]

In [12]:
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[1:6:2])

[1 3 5]


---

In [13]:
arr = np.random.rand(4, 4, 4)
print(arr[..., 0])

[[0.15577195 0.19686848 0.30490649 0.22837442]
 [0.98469979 0.1997237  0.66249328 0.54289015]
 [0.15420497 0.38026869 0.81648129 0.34852919]
 [0.70411632 0.79494691 0.32871879 0.70547179]]


---

In [14]:
arr = np.array([1, 2, 0, 4, 5, 3])

idx = np.array([1, 3, 5])
print (arr[idx])

print (arr[(arr != 0) | (arr == 0)])

[2 4 3]
[1 2 0 4 5 3]


---

In [15]:
arr = np.array([1, 2, 3])
print(arr[:, np.newaxis])

[[1]
 [2]
 [3]]


---

In [16]:
arr = np.array([1, 2, 3, 4])
arr[1:3] = 99
print(arr)

[ 1 99 99  4]


---
### Arithmetic Operations in NumPY Arrays

In [17]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


---
### Absolute in NumPY

In [18]:
arr = np.array([-3, -1, 0, 1, 3])
res = np.absolute(arr)

print(res)

[3 1 0 1 3]


---
### Add in Numpy

In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
res = np.add(arr1, arr2)

print(res)

[5 7 9]


---
### Exponentiation in NumPY

In [20]:
arr1 = np.array([5, 72, 13, 100])
arr2 = np.array([2, 5, 10, 30])

res = np.power(arr1, arr2)
print(res)

[                 25          1934917632        137858491849
 1152921504606846976]


---
### Modulus in NumPY

In [21]:
arr1 = np.array([5, 72, 13, 100])
arr2 = np.array([2, 5, 10, 30])

res = np.mod(arr1, arr2)
print(res)

[ 1  2  3 10]


---
### Sine / Exponential / Square Root in NumPy

In [22]:
a = np.array([0, np.pi/2, np.pi])
print(np.sin(a))
print(np.exp(a))
print(np.sqrt(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          4.81047738 23.14069263]
[0.         1.25331414 1.77245385]


---
### Sorting NumPY Arrays

In [23]:
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
          ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

arr = np.array(values, dtype = dtypes)

print (np.sort(arr, order = 'name'))
print (np.sort(arr, order = ['grad_year', 'cgpa']))

[(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
[(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


---
### Type Of NumPY Arrays

In [24]:
arr = np.array([1, 2, 3])
print(type(arr))

<class 'numpy.ndarray'>


---
### Shape / Size / DataType of NumPY Arrays

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape :", arr.shape)
print("Size :", arr.size)
print("D Type :", arr.dtype)

Shape : (2, 3)
Size : 6
D Type : int64


---
### Formiter in NumPY

In [26]:
var = "RafatAlam"
arr = np.fromiter(var, dtype = 'U2')

print(arr)

['R' 'a' 'f' 'a' 't' 'A' 'l' 'a' 'm']


---
### Random In NumPY

Fills values with random values between [0, 1)

In [27]:
arr = np.random.rand(2, 3)
print(arr)

[[0.93031459 0.28573189 0.96587083]
 [0.65006392 0.49239461 0.83980496]]


---
Fill values with standard Normal Distribution

In [28]:
arr = np.random.randn(2, 2)
print(arr)

[[ 0.68286228  0.32490147]
 [ 0.09169063 -0.13499802]]


---
Fills values with random integers between [a, b)

In [29]:
arr = np.random.randint(1, 10, size = [2, 3])
print(arr)

[[2 7 1]
 [9 6 5]]


---
### Matrix creation in NumPY
Identity Matrix

In [30]:
arr = np.eye(3, dtype = np.int64)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


---
Diagonal Matrix

In [31]:
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


---
Zero Array

In [32]:
arr = np.zeros_like(arr) # Pass array it will take shape of that
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


---
One's Array

In [33]:
arr = np.ones_like(arr) # Pass array it will take shape of that
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


---
### Reshaping Arrays

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print(str(arr))

res = arr.reshape((2, 8))
print(res)
res = np.reshape(arr, [4, -1])
print(res)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


---
### Resizing Arrays
Permanent Array Reshaping

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize(2, 3)
print(arr)

[[1 2 3]
 [4 5 6]]


---