## 03 - Array Broadcasting
---
Importing NumPY

In [2]:
import numpy as np

---
Operation always happens row-wise

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

print(a + b)

[[2 4 6]
 [5 7 9]]


---


By using np.newaxis, we can add elements column-wise

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])

print(a + b[:, np.newaxis])

[[2 3 4]
 [6 7 8]]


---
### Broadcasting in Conditional Operations

In [6]:
ages = np.array([12, 24, 35, 45, 60, 72])
age_group = np.array(["Adult", "Minor"])

res = np.where(ages >= 18, age_group[0], age_group[1])
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


---
### Normalizing Data in ML
- centers data and it has zero mean.
- By dividing the standard deviation, its ensures unit variance.

In [7]:
arr = np.array([
  [100, 120, 130],
  [90, 110, 140],
  [80, 100, 120]
])

mean = arr.mean(axis = 0)
std = arr.std(axis = 0)

normalized_arr = (arr - mean) / std
print(normalized_arr)

[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


---
### Centering Data in ML

In [8]:
arr = np.array([
  [10, 20],
  [15, 25],
  [20, 30]
])

mean = arr.mean(axis = 0)
centered_arr = arr - mean
print(centered_arr)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]


---