## 04 - Aggregation / Universal Functions
---
Importing NumPY

In [22]:
import numpy as np

---
## Sum in NumPY

In [23]:
arr = [20, 2, .2, 10, 4] 

print("Sum :", np.sum(arr))
print("Data Type :", np.sum(arr).dtype)

print("Sum (int32) :", np.sum(arr, dtype = np.int32))

Sum : 36.2
Data Type : float64
Sum (int32) : 36


---

In [24]:
arr = [[14, 17, 12, 33, 44],
	     [15, 6, 27, 8, 19],
	     [23, 2, 54, 1, 4,]]

print("Sum :", np.sum(arr))
print("Data Type :", np.sum(arr).dtype)

Sum : 279
Data Type : int64


---

In [25]:
arr = [[14, 17, 12, 33, 44],
	     [15, 6, 27, 8, 19],
	     [23, 2, 54, 1, 4,]]

print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))
print(np.sum(arr, axis = 1, keepdims = True))

[52 25 93 42 67]
[120  75  84]
[[120]
 [ 75]
 [ 84]]


---
### Mean in NumPY

In [26]:
arr = [20, 2, 7, 1, 34]
print(np.mean(arr))

12.8


---

In [27]:
arr = [[14, 17, 12, 33, 44],  
       [15, 6, 27, 8, 19], 
       [23, 2, 54, 1, 4]]

print(np.mean(arr))
print(np.mean(arr, axis = 0))
print(np.mean(arr, axis = 1))

18.6
[17.33333333  8.33333333 31.         14.         22.33333333]
[24.  15.  16.8]


---
### Max / Min in NumPY

In [28]:
num1 = 11
num2 = 21

res = np.maximum(num1, num2)
print(res)
res = np.minimum(num1, num2)
print(res)

21
11


---

In [29]:
num1 = [2, 8, 125]
num2 = [3, 3, 15]

res = np.maximum(num1, num2)
print(res)
res = np.minimum(num1, num2)
print(res)

[  3   8 125]
[ 2  3 15]


---

In [30]:
num1 = [np.nan, 0, np.nan]
num2 = [np.nan, np.nan, 0]

res = np.maximum(num1, num2)
print(res)
res = np.minimum(num1, num2)
print(res)

[nan nan nan]
[nan nan nan]


---
### Trignometric Functions

In [39]:
angles = np.array([0, 30, 45, 60, 90, 180]) 

radians = np.deg2rad(angles)

# sine of angles
sine = np.sin(radians)
print(np.sin(radians))

# inverse sine of sine values
print(np.rad2deg(np.arcsin(sine)))

# hyperbolic sine of angles
sineh = np.sinh(radians)
print(np.sinh(radians))

# inverse sine hyperbolic 
print(np.sin(sineh)) 

# hypotenuse
print(np.hypot(3, 4))

[0.00000000e+00 5.00000000e-01 7.07106781e-01 8.66025404e-01
 1.00000000e+00 1.22464680e-16]
[0.0000000e+00 3.0000000e+01 4.5000000e+01 6.0000000e+01 9.0000000e+01
 7.0167093e-15]
[ 0.          0.54785347  0.86867096  1.24936705  2.3012989  11.54873936]
[ 0.          0.52085606  0.76347126  0.94878485  0.74483916 -0.85086591]
5.0


---
### Statical Functions

In [36]:
arr = np.array([50.7, 52.5, 50, 58, 55.63, 73.25, 49.5, 45])

# minimum and maximum 
print(np.amin(arr), np.amax(arr))

# range of arr i.e. max - min
print(np.ptp(arr))

# percentile -> Value below which 70 % student fall
print(np.percentile(arr, 70))
 
# mean 
print(np.mean(arr))

# median 
print(np.median(arr))

# standard deviation 
print(np.std(arr))

# variance 
print(np.var(arr))

# average 
print(np.average(arr))

45.0 73.25
28.25
55.317
54.3225
51.6
8.052773978574091
64.84716875
54.3225


---
### Bit-twiddling Functions

In [37]:
even = np.array([0, 2, 4, 6, 8, 16, 32])
odd = np.array([1, 3, 5, 7, 9, 17, 33])

# bitwise_and
print(np.bitwise_and(even, odd))

# bitwise_or
print(np.bitwise_or(even, odd))

# bitwise_xor
print(np.bitwise_xor(even, odd))
 
# invert or not
print(np.invert(even))

# left_shift 
print(np.left_shift(even, 1))

# right_shift 
print(np.right_shift(even, 1))

[ 0  2  4  6  8 16 32]
[ 1  3  5  7  9 17 33]
[1 1 1 1 1 1 1]
[ -1  -3  -5  -7  -9 -17 -33]
[ 0  4  8 12 16 32 64]
[ 0  1  2  3  4  8 16]


---