## 07 - Sparse Matrix with SciPY
---
Importing Modules

In [12]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix, coo_matrix, lil_matrix, dok_matrix, dia_matrix

---
### CSR MATRIX
Compressed Sparse Row good for arithmetic and row access.

In [13]:
d = np.array([3, 4, 5, 7, 2, 6])     # data
r = np.array([0, 0, 1, 1, 3, 3])     # rows
c = np.array([2, 4, 2, 3, 1, 2])     # cols

csr = csr_matrix((d, (r, c)), shape = [4, 5])
print(csr.toarray())

[[0 0 3 0 4]
 [0 0 5 7 0]
 [0 0 0 0 0]
 [0 2 6 0 0]]


---
### CSC MATRIX
Compressed Sparse Column efficient for column-based ops.

In [14]:
d = np.array([3, 4, 5, 7, 2, 6])     # data
r = np.array([0, 0, 1, 1, 3, 3])     # rows
c = np.array([2, 4, 2, 3, 1, 2])     # cols

csr = csc_matrix((d, (r, c)), shape = [4, 5])
print(csr.toarray())

[[0 0 3 0 4]
 [0 0 5 7 0]
 [0 0 0 0 0]
 [0 2 6 0 0]]


---
### COO MATRIX
Coordinate format using (row, col, value) triples.

In [15]:
d = np.array([3, 4, 5, 7, 2, 6]) # data
r = np.array([0, 0, 1, 1, 3, 3]) # rows 
c = np.array([2, 4, 2, 3, 1, 2]) # cols

coo = coo_matrix((d, (r, c)), shape = [4, 5])
print(coo.toarray())

[[0 0 3 0 4]
 [0 0 5 7 0]
 [0 0 0 0 0]
 [0 2 6 0 0]]


---
### LIL MATRIX
List of Lists, modify rows easily before converting.

In [16]:
lil = lil_matrix((4, 5))
lil[0, 2] = 3
lil[0, 4] = 4
lil[1, 2] = 5
lil[1, 3] = 7
lil[3, 1] = 2
lil[3, 2] = 6

print(lil.toarray())

[[0. 0. 3. 0. 4.]
 [0. 0. 5. 7. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 6. 0. 0.]]


---
### DOK MATRIX
Dictionary-like, ideal for random updates.

In [17]:
dok = dok_matrix((4, 5))
dok[0, 2] = 3
dok[0, 4] = 4
dok[1, 2] = 5
dok[1, 3] = 7
dok[3, 1] = 2
dok[3, 2] = 6

print(dok.toarray())

[[0. 0. 3. 0. 4.]
 [0. 0. 5. 7. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 6. 0. 0.]]


---
### DIA (Diagonal) MATRIX
Stores only diagonals, saves space.

In [18]:
d = np.array([[3, 0, 0, 0, 0], [0, 5, 0, 0, 0]])
offsets = np.array([0, -1])  
dia = dia_matrix((d, offsets), shape = [4, 5])

print(dia.toarray())

[[3 0 0 0 0]
 [0 0 0 0 0]
 [0 5 0 0 0]
 [0 0 0 0 0]]


---