## 02 - Stacking and Splitting Arrays
---

Importing NumPY

In [38]:
import numpy as np

---
### Stacking 2 [1-D Arrays]

In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

res = np.stack((arr1, arr2), axis = 0)
print(res)

[[1 2 3]
 [4 5 6]]


In [40]:
res = np.stack((arr1, arr2), axis = 1)
print(res)

[[1 4]
 [2 5]
 [3 6]]


In [41]:
res = np.stack((arr1, arr2), axis = -1) # -1 represents 'last dimension-wise'. Here 2 axis are possible. 0 and 1. So, -1 is same as 1.
print(res)

[[1 4]
 [2 5]
 [3 6]]


---
### Splitting Arrays in NumPY

In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
res = np.array_split(arr, 3)
print(res)

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [43]:
arr = np.array([[3, 2, 1], [8, 9, 7], [4, 6, 5]])
res = np.split(arr, 3, axis = 1)
print(res)

[array([[3],
       [8],
       [4]]), array([[2],
       [9],
       [6]]), array([[1],
       [7],
       [5]])]


---
V-Split is for axis = 0

In [44]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

res = np.vsplit(arr, 2)
print(res)
res = np.split(arr, 2, axis = 0)
print(res)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


---
H-Split is for axis = 1

In [45]:
res = np.hsplit(arr, 2)
print(res)
res = np.split(arr, 2, axis = 1)
print(res)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


---
D-Split is for axis = 2

In [46]:
arr = np.array([[[0, 1, 2, 3],
                 [4, 5, 6, 7],
                 [8, 9, 10, 11]],

                [[12, 13, 14, 15],
                 [16, 17, 18, 19],
                 [20, 21, 22, 23]]])

res = np.dsplit(arr, 2)
print(res)

[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


---