## 05 - Linear Algebra with NumPY
---
Importing NumPY

In [7]:
import numpy as np

---
### Transpose of Matrix

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


---
### Matrix Multiplication / Dot Product

In [18]:
arr1 = np.array([[1, 2], [4, 5]])
arr2 = np.array([[7, 8], [9, 10]])

print(np.dot(arr1, arr2))
print(np.vdot(arr1, arr2)) # It assumes array to be flattened

vector_a = 2 + 3j
vector_b = 4 + 5j

print(np.dot(vector_a, vector_b))
print(np.vdot(vector_a, vector_b)) # It will take conjugate of complex numbers for dot product

[[25 28]
 [73 82]]
109
(-7+22j)
(23-2j)


---
### Inner Product

In [10]:
arr1 = np.array([2, 6])     # 1 x 2
arr2 = np.array([3, 10])    # 2 x 1

print(np.inner(arr1, arr2)) # 1 x 1

arr1 = np.array([[2, 3, 4], [3, 2, 9]])  # 2 x 3
arr2 = np.array([[1, 5, 0], [5, 10, 3]]) # 3 x 2

print(np.inner(arr1, arr2))              # 2 x 2

66
[[17 52]
 [13 62]]


---
### Outer Product

In [11]:
arr1 = np.array([2, 6])
arr2 = np.array([3, 10])

print(np.outer(arr1, arr2))

arr1 = np.array([[3, 6, 4], [9, 4, 6]])
arr2 = np.array([[1, 15, 7], [3, 10, 8]])

print(np.outer(arr1, arr2))

[[ 6 20]
 [18 60]]
[[  3  45  21   9  30  24]
 [  6  90  42  18  60  48]
 [  4  60  28  12  40  32]
 [  9 135  63  27  90  72]
 [  4  60  28  12  40  32]
 [  6  90  42  18  60  48]]


---
### Cross Product

In [12]:
arr1 = np.array([3, 6, 0])
arr2 = np.array([9, 10, 0])

print(np.cross(arr1, arr2))

arr1 = np.array([[2, 6, 9], [2, 7, 3]])
arr2 = np.array([[7, 5, 6], [3, 12, 3]])

print(np.cross(arr1, arr2))

[  0   0 -24]
[[ -9  51 -32]
 [-15   3   3]]


---
### Dterminant of a Matrix
Using log of determinant

In [13]:
arr = np.array([[50, 29], [30, 44]])
sign, logdet = np.linalg.slogdet(arr)
res = sign * np.exp(logdet)
print(res)

1330.0000000000002


---
Using simple Determinant (Used for small values)

In [14]:
arr = np.array([[1, 2], [3, 4]])
res = np.linalg.det(arr)
print(res)

-2.0000000000000004


---
__Using LU Decomposition :__ LU decomposition can also be used to calculate the determinant by decomposing the matrix into lower (L) and upper (U) triangular matrices. The determinant is the product of the diagonal elements of the U matrix.

In [15]:
import scipy.linalg
arr = np.array([[1, 2], [3, 4]])
P, L, U = scipy.linalg.lu(arr)
res = np.prod(np.diag(U))
print(res)

2.0


---
### Inverse of a Matrix

In [ ]:
arr = np.array([[6, 1, 1],
                [4, -2, 5],
                [2, 8, 7]])
print(np.linalg.inv(arr))

---