## 01 - Introduction To NumPY

---
Importing NumPY

In [37]:
import numpy as np

---
### Initialization of Array in NumPY
From Python Lists

In [38]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


---
Array with Evenly Spaced Numbers

Syntax -> numpy.linspace(start, stop, num = 50, endpoint = True, retstep = False, dtype = None, axis = 0)

In [39]:
arr = np.linspace(3.5, 10, 3, dtype = np.float64)
print(arr)

[ 3.5   6.75 10.  ]


---
Array with Garbage Value

In [40]:
arr = np.empty([4, 3], dtype = np.int32, order = 'f')
print(arr)

[[1 3 5]
 [0 0 0]
 [2 4 6]
 [0 0 0]]


---
Array with Zeros

In [41]:
arr = np.zeros([2, 3], dtype = np.int32, order = 'f') # [Dimension of Array]
print(arr)

[[0 0 0]
 [0 0 0]]


---
Array with Ones

In [42]:
arr = np.ones((2, 2), dtype = np.int32, order = 'f') # [Dimension of Array]
print(arr)

[[1 1]
 [1 1]]


---
Array with All Values Equal

In [43]:
arr = np.full((2, 2), 7)
print(arr)

[[7 7]
 [7 7]]


---
Array with Range Values

In [44]:
arr = np.arange(0, 10, 2, dtype = np.int64) # (start, end, steps), end is excluded
print(arr)

[0 2 4 6 8]


---
### Indexing in NumPY

In 1D Array

In [45]:
arr = np.array([10, 20, 30, 40, 50])
              #  0,  1,  2,  3,  4
              # -5, -4, -3, -2, -1
print(arr[2])
print(arr[-1])

30
50


---
In 2D Array

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[1, 0]) # [Row, Column]

4


---

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# all rows, second column
print(arr[:, 1])
# [2 5]
print(arr[:, [1]])
# [[2]
#  [5]]

# all, rows, second and third column
print(arr[:, [1, 2]])
# [[2 3]
#  [5 6]]

[2 5]
[[2]
 [5]]
[[2 3]
 [5 6]]


---
[start:stop(excluded):steps]

In [48]:
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[1:6:2])

[1 3 5]


---

In [49]:
arr = np.random.rand(4, 4, 4)
print(arr[..., 0])

[[0.86714978 0.27618055 0.58027235 0.96320792]
 [0.59663365 0.05518922 0.35365668 0.84440147]
 [0.3721065  0.62578283 0.37158913 0.76214109]
 [0.96588863 0.87112971 0.95110154 0.51379705]]


---

In [50]:
arr = np.array([1, 2, 0, 4, 5, 3])

idx = np.array([1, 3, 5])
print (arr[idx])

print (arr[(arr != 0) | (arr == 0)])

[2 4 3]
[1 2 0 4 5 3]


---

In [51]:
arr = np.array([1, 2, 3])
print(arr[:, np.newaxis])

[[1]
 [2]
 [3]]


---

In [52]:
arr = np.array([1, 2, 3, 4])
arr[1:3] = 99
print(arr)

[ 1 99 99  4]


---
### Arithmetic Operations in NumPY Arrays

In [53]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)
print(x - y)
print(x * y)
print(x / y)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


---
### Absolute in NumPY

In [54]:
arr = np.array([-3, -1, 0, 1, 3])
res = np.absolute(arr)

print(res)

[3 1 0 1 3]


---
### Add in Numpy

In [55]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
res = np.add(arr1, arr2)

print(res)

[5 7 9]


---
### Exponentiation in NumPY

In [56]:
arr1 = np.array([5, 72, 13, 100])
arr2 = np.array([2, 5, 10, 30])

res = np.power(arr1, arr2)
print(res)

[                 25          1934917632        137858491849
 1152921504606846976]


---
### Modulus in NumPY

In [57]:
arr1 = np.array([5, 72, 13, 100])
arr2 = np.array([2, 5, 10, 30])

res = np.mod(arr1, arr2)
print(res)

[ 1  2  3 10]


---
### Sine / Exponential / Square Root in NumPy

In [58]:
a = np.array([0, np.pi/2, np.pi])
print(np.sin(a))
print(np.exp(a))
print(np.sqrt(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          4.81047738 23.14069263]
[0.         1.25331414 1.77245385]


---
### Sorting NumPY Arrays

In [59]:
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
          ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

arr = np.array(values, dtype = dtypes)

print (np.sort(arr, order = 'name'))
print (np.sort(arr, order = ['grad_year', 'cgpa']))

[(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
[(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


---
### Type Of NumPY Arrays

In [60]:
arr = np.array([1, 2, 3])
print(type(arr))

<class 'numpy.ndarray'>


---
### Shape / Size / DataType of NumPY Arrays

In [61]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape :", arr.shape)
print("Size :", arr.size)
print("D Type :", arr.dtype)

Shape : (2, 3)
Size : 6
D Type : int64


---
### Formiter in NumPY

In [62]:
var = "RafatAlam"
arr = np.fromiter(var, dtype = 'U2')

print(arr)

['R' 'a' 'f' 'a' 't' 'A' 'l' 'a' 'm']


---
### Random In NumPY

Fills values with random values between [0, 1)

In [63]:
arr = np.random.rand(2, 3)
print(arr)

[[0.1783931  0.96170809 0.20628133]
 [0.11441714 0.37252242 0.72725007]]


---
Fill values with standard Normal Distribution

In [64]:
arr = np.random.randn(2, 2)
print(arr)

[[ 1.19111212  0.45825831]
 [ 0.10448525 -0.3273026 ]]


---
Fills values with random integers between [a, b)

In [65]:
arr = np.random.randint(1, 10, size = [2, 3])
print(arr)

[[5 5 2]
 [6 4 1]]


---
### Matrix creation in NumPY
Identity Matrix

In [66]:
arr = np.eye(3, dtype = np.int64)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


---
Diagonal Matrix

In [67]:
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


---
Zero Array

In [68]:
arr = np.zeros_like(arr) # Pass array it will take shape of that
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


---
One's Array

In [69]:
arr = np.ones_like(arr) # Pass array it will take shape of that
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


---
### Reshaping Arrays

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print(str(arr))

res = arr.reshape((2, 8))
print(res)
res = np.reshape(arr, [4, -1])
print(res)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


---
### Flatten vs Ravel

In [73]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

res = arr.flatten() # Creates Copy
print(res)
print(arr.ravel())  # Not a Copy

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


---
### Resizing Arrays
Permanent Array Reshaping

In [71]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize(2, 3)
print(arr)

[[1 2 3]
 [4 5 6]]


---
### Type-casting in NumPY

In [72]:
a = np.array([1.1, 2.2, 3.3])
a = a.astype(int)

print(a)

[1 2 3]


---
### Inserting Values in NumPY

In [ ]:
arr = np.array([1, 2, 3, 4])
res = np.insert(arr, 3, 33, axis = None)
print(res)

[ 1  2  3 33  4]


---

In [79]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

res1 = np.insert(arr, 2, 33, axis = 0)
print(res1)

res2 = np.insert(arr, 2, [33, 44], axis = 1)
print(res2)

[[ 1  2  3]
 [ 4  5  6]
 [33 33 33]]
[[ 1  2 33  3]
 [ 4  5 44  6]]


---
### Deleting Values in NumPY

In [82]:
arr = np.array([1, 2, 3, 4])
res = np.delete(arr, 2, axis = None)
print(res)

[1 2 4]


---
### Identify missing values in Data Sets

In [93]:
arr = np.array([1, 2, np.nan, 4, np.nan])
print(np.isnan(arr))

res = np.nan_to_num(arr, nan = 0)
print(res)

[False False  True False  True]
[1. 2. 0. 4. 0.]


---
### Identifying Infinite values in Data Set

In [95]:
arr = np.array([1, 2, np.inf, 4, -np.inf])
print(np.isinf(arr))

res = np.nan_to_num(arr, posinf = 0, neginf = 0)
print(res)

[False False  True False  True]
[1. 2. 0. 4. 0.]


---